// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FNjNldiNAptbbvOfZi6LGJNDDo64AAU',
    appId: '1:1042655623131:web:345ec9cccd4720e6f719fe',
    messagingSenderId: '1042655623131',
    projectId: 'mybiz-aae0e',
    authDomain: 'mybiz-aae0e.firebaseapp.com',
    storageBucket: 'mybiz-aae0e.firebasestorage.app',
    measurementId: 'G-0WNHDP6WJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVrIIKL--C6G5cmSFhsLi76J0YUY5Wps',
    appId: '1:1042655623131:android:38bff255ce1122ebf719fe',
    messagingSenderId: '1042655623131',
    projectId: 'mybiz-aae0e',
    storageBucket: 'mybiz-aae0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWGvPhPil8g1InfeQGrrdMEM3dTtnHF0',
    appId: '1:1042655623131:ios:a5cbba74d012374df719fe',
    messagingSenderId: '1042655623131',
    projectId: 'mybiz-aae0e',
    storageBucket: 'mybiz-aae0e.firebasestorage.app',
    iosBundleId: 'com.example.mybiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWGvPhPil8g1InfeQGrrdMEM3dTtnHF0',
    appId: '1:1042655623131:ios:a5cbba74d012374df719fe',
    messagingSenderId: '1042655623131',
    projectId: 'mybiz-aae0e',
    storageBucket: 'mybiz-aae0e.firebasestorage.app',
    iosBundleId: 'com.example.mybiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2FNjNldiNAptbbvOfZi6LGJNDDo64AAU',
    appId: '1:1042655623131:web:ed2fb4d4e52fe280f719fe',
    messagingSenderId: '1042655623131',
    projectId: 'mybiz-aae0e',
    authDomain: 'mybiz-aae0e.firebaseapp.com',
    storageBucket: 'mybiz-aae0e.firebasestorage.app',
    measurementId: 'G-5RFE463M45',
  );
}
